/**
 * Image-lane bake-off harness.
 *
 * READ-ONLY against real user data: it copies app.db and lance/ into a scratch
 * dir and opens blobs/ without writing. Nothing here touches the live store —
 * the same principle as scripts/replay-probe.mjs wrapping its Actuator, and
 * verified the same way (hash the real app.db before and after).
 *
 *   node scripts/imagelane-probe.mjs --spaces             # what is already indexed
 *   node scripts/imagelane-probe.mjs --propose            # draft ground truth
 *   node scripts/imagelane-probe.mjs --frames <outDir>    # extract keyframes for review
 *   node scripts/imagelane-probe.mjs --run <models-dir>   # score every candidate
 *
 * --run options:
 *   --sessions <n>   only the first n sessions (a smoke run; the full sweep is hours)
 *   --only <name>    one candidate by name, repeatable
 *   --skip-index     reuse vectors already in the scratch copy (only with --scratch)
 *   --scratch <dir>  reuse an earlier scratch copy instead of making a new one
 *
 * Requires `npm run build` first (imports dist/).
 */

import { cpSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";
import { DualStore } from "../dist/store/store.js";
import { BlobStore } from "../dist/store/blob-store.js";

export const DATA_DIR =
  process.env.DESKRAG_DATA_DIR ??
  join(homedir(), "Library", "Application Support", "deskrag-app", "DeskRAG");

const arg = (flag, fallback) => {
  const i = process.argv.indexOf(flag);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : fallback;
};
const has = (flag) => process.argv.includes(flag);

/** Copy the relational + vector stores so the real ones are never written. */
export function openScratchCopy() {
  const dir = mkdtempSync(join(tmpdir(), "deskrag-bakeoff-"));
  cpSync(join(DATA_DIR, "app.db"), join(dir, "app.db"));
  for (const suffix of ["-wal", "-shm"]) {
    try {
      cpSync(join(DATA_DIR, `app.db${suffix}`), join(dir, `app.db${suffix}`));
    } catch {
      /* absent when the app is closed — normal */
    }
  }
  cpSync(join(DATA_DIR, "lance"), join(dir, "lance"), { recursive: true });
  return dir;
}

const openStore = (dir) => DualStore.open(join(dir, "app.db"), join(dir, "lance"));

async function spaces() {
  const dir = arg("--scratch", null) ?? openScratchCopy();
  const store = await openStore(dir);
  console.log(`scratch: ${dir}`);
  for (const s of store.listVectorSpaces()) {
    console.log(`  ${s.namespace}  view=${s.view} dims=${s.dimensions}`);
  }
  const sessions = store.listSessions();
  console.log(`\n${sessions.length} sessions`);
  for (const s of sessions) {
    console.log(
      `  ${s.id}  frames=${s.frameCount ?? "?"} segments=${s.segmentCount ?? "?"}  ${s.startedAt ?? ""}`,
    );
  }
  store.close();
}

/**
 * Draft candidate queries from AX labels — evidence of what a frame shows that
 * is INDEPENDENT of any image model, because those labels are literally
 * rendered on screen. Captions are deliberately not used: they are a VLM's
 * output, and ground truth generated by one model flatters models that agree
 * with it.
 *
 * Labels are chosen by DISTINCTIVENESS, not by tree order, and a proposal is
 * only emitted when its evidence names EXACTLY ONE frame in the library. Taking
 * the first three labels instead — the obvious approach, and the first one
 * tried — proposed 526 queries of which most were duplicates: "Calculator, Edit
 * field, Delete" describes every frame of a Calculator session equally well, so
 * it is not known-answer and a human reviewer can only delete it. Uniqueness is
 * the property the whole measurement rests on, so it is computed here rather
 * than left for a person to notice 500 times.
 */
/**
 * Evidence that must never leave the store, and the reason is specific rather
 * than precautionary: a window TITLE is user screen content, and a Terminal
 * titles itself with the running command line. One recording here carried
 * `claude mcp add … --header Authorization: Bearer <token>` as a window title,
 * the rarest-term rule picked it as ideal evidence, and it landed in a
 * committed fixture. Anything derived from a recording can carry a credential,
 * so the term is DROPPED rather than masked — a title holding a token is not
 * usable evidence either way.
 */
const SECRET_PATTERNS = [
  /bearer\s+\S+/i,
  /\b(api[-_ ]?key|secret|password|passwd|credential)\b/i,
  /\b[A-Fa-f0-9]{20,}\b/,
  /\b(sk|pk|ghp|gho|github_pat|xox[baprs])[-_][A-Za-z0-9]{10,}/,
  /\baccess[-_ ]?token\b/i,
];
const looksSecret = (term) => SECRET_PATTERNS.some((re) => re.test(term));

/** Latest at-or-before, the rule every environment fact in this repo resolves by. */
function latestAtOrBefore(sorted, tMono) {
  let out;
  for (const e of sorted) {
    if (e.tMono > tMono) break;
    out = e;
  }
  return out;
}

/** How many frames a query may legitimately name before it stops discriminating. */
const MAX_RELEVANT = 5;

async function propose() {
  const dir = openScratchCopy();
  const store = await openStore(dir);

  // Pass 1: each frame's evidence set, and how many frames each term appears on.
  // Window title and URL join the AX labels because they are on screen too (title
  // bar, address bar) and, unlike a caption, no model produced them.
  const frames = [];
  const df = new Map();
  for (const s of store.listSessions()) {
    const events = store.getEventsBySession(s.id);
    const focus = events.filter((e) => e.kind === "focus_change");
    const urls = events.filter((e) => e.kind === "url_change");

    for (const frame of store.getFramesBySession(s.id)) {
      const terms = new Set(
        store
          .getFrameAx(frame.id)
          .map((e) => (e.label ?? "").trim())
          .filter((l) => l.length >= 4 && l.length <= 60),
      );
      const f = latestAtOrBefore(focus, frame.tMono);
      const title = f?.data?.title?.trim();
      const app = f?.data?.app?.trim();
      if (title && title.length >= 4) terms.add(title);
      if (app && app.length >= 3) terms.add(app);
      const u = latestAtOrBefore(urls, frame.tMono);
      const url = u?.data?.url?.trim();
      if (url && url.length >= 8 && !url.startsWith("about:")) terms.add(url);

      for (const t of [...terms]) if (looksSecret(t)) terms.delete(t);
      if (terms.size === 0) continue;
      frames.push({ frame, sessionId: s.id, terms });
      for (const t of terms) df.set(t, (df.get(t) ?? 0) + 1);
    }
  }

  // Pass 2: rarest terms first, adding until the evidence names few enough
  // frames to discriminate.
  //
  // GROUND TRUTH IS A RELEVANT SET, NOT ONE FRAME — a deviation from the plan,
  // forced by measurement. Requiring exactly one frame yielded THREE queries
  // from 526 frames, because DeskRAG samples roughly one keyframe per second and
  // consecutive frames of one screen carry identical labels. Those frames are
  // not distinguishable by a person either, so demanding that a retriever pick
  // between them measures nothing. A query whose evidence names up to
  // MAX_RELEVANT frames keeps its known-answer meaning ("any of these is the
  // screen I meant") while still discriminating against the other ~520.
  const out = [];
  const tooBroad = [];
  for (const f of frames) {
    const ranked = [...f.terms].sort((a, b) => (df.get(a) ?? 0) - (df.get(b) ?? 0));
    const chosen = [];
    let matches = frames;
    for (const term of ranked) {
      if (chosen.length >= 4) break;
      chosen.push(term);
      matches = matches.filter((o) => o.terms.has(term));
      if (matches.length === 1) break;
    }
    const entry = {
      text: `the screen showing ${chosen.join(", ")}`,
      frameIds: matches.map((m) => m.frame.id),
      sessionId: f.sessionId,
      _evidence: chosen,
      _rarest: df.get(chosen[0]) ?? 0,
      _relevant: matches.length,
      _tMono: f.frame.tMono,
    };
    (matches.length <= MAX_RELEVANT ? out : tooBroad).push(entry);
  }

  // One entry per distinct relevant SET: 4 frames of one screen otherwise
  // produce 4 identical queries, which would weight that screen 4x in the mean.
  const seen = new Set();
  const deduped = out.filter((q) => {
    const key = [...q.frameIds].sort().join(",");
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
  // The visual-example arm falls straight out of the same computation: a
  // relevant set of size >= 2 IS two frames of one UI state, which is exactly
  // what Task 5 Step 4 asks a human to find by hand. One pair per set, and the
  // query frame is excluded from its own results at scoring time.
  const visualQueries = deduped
    .filter((q) => q.frameIds.length >= 2)
    .map((q) => ({
      queryFrameId: q.frameIds[0],
      expectFrameId: q.frameIds[1],
      sessionId: q.sessionId,
      _evidence: q._evidence,
    }));
  store.close();

  writeFileSync(
    "test/fixtures/imagelane-queries.draft.json",
    JSON.stringify(
      {
        note:
          "DRAFT — review by hand (Task 5 Step 3): rewrite each text as a person would " +
          "type it, delete anything ambiguous, keep the mix of frame kinds honest, " +
          "then strip the _ fields and save as imagelane-queries.json. `frameIds` is " +
          "the set of ACCEPTABLE answers; a hit on any of them counts.",
        queries: deduped,
        visualQueries,
      },
      null,
      2,
    ),
  );
  console.log(`  ${visualQueries.length} visual pairs (two frames of one state)`);
  const sessions = new Set(deduped.map((q) => q.sessionId)).size;
  console.log(
    `proposed ${deduped.length} queries (<=${MAX_RELEVANT} relevant frames each) across ${sessions} sessions`,
  );
  console.log(`  ${out.length - deduped.length} dropped as duplicate relevant sets`);
  console.log(`  ${tooBroad.length} frames have no evidence narrow enough to discriminate`);
  console.log(`scratch: ${dir}`);
}

/**
 * Extract every proposed frame's keyframe JPEG plus an index.html, because the
 * review step in Task 5 needs to LOOK at the frame a query names and
 * `deskrag://frame/` is not reachable from a script. Local files only — these
 * are real screenshots of the user's desktop and never leave the machine.
 */
async function extractFrames(outDir) {
  const draftPath = "test/fixtures/imagelane-queries.draft.json";
  const draft = JSON.parse(readFileSync(draftPath, "utf8"));
  const dir = openScratchCopy();
  const store = await openStore(dir);
  const blobs = new BlobStore(join(DATA_DIR, "blobs"));
  mkdirSync(outDir, { recursive: true });

  // EVERY frame of the relevant set is rendered, not just the first: the review
  // question is "would any of these be a correct answer", which cannot be judged
  // from one thumbnail.
  const rows = [];
  const written = new Set();
  for (const [i, q] of draft.queries.entries()) {
    const files = [];
    for (const frameId of q.frameIds ?? [q.frameId]) {
      const frame = store.getFrame(frameId);
      const blob = frame?.blobId ? store.getBlob(frame.blobId) : undefined;
      if (!blob) continue;
      const name = `${frameId}.jpg`;
      if (!written.has(name)) {
        writeFileSync(join(outDir, name), await blobs.read(blob));
        written.add(name);
      }
      files.push(name);
    }
    if (files.length > 0) rows.push({ ...q, files, index: i });
  }
  store.close();

  const esc = (s) => String(s).replace(/[&<>"]/g, (c) => `&#${c.charCodeAt(0)};`);
  writeFileSync(
    join(outDir, "index.html"),
    `<!doctype html><meta charset=utf8><title>image-lane query review</title>
<style>
 body{font:13px/1.5 -apple-system,sans-serif;background:#12151a;color:#e6e9ef;margin:0;padding:24px}
 h1{font-size:20px} h1 small{color:#98a2b3;font-weight:400;font-size:13px;display:block;margin-top:6px}
 .card{border:1px solid #2a2f38;border-radius:10px;padding:12px;margin:12px 0;background:#171b21}
 .shots{display:flex;gap:8px;overflow-x:auto;margin-top:10px}
 img{height:200px;border-radius:6px;border:1px solid #2a2f38}
 code{background:#0e1116;padding:1px 5px;border-radius:4px;font-size:11px}
 .q{font-size:15px;margin:0 0 6px} .meta{color:#98a2b3;font-size:11px;margin:2px 0}
</style>
<h1>${rows.length} proposed queries
<small>Rewrite each text as you would actually type it. Delete any whose answer is
ambiguous — if a frame outside its row would also be correct, it is not
known-answer. Keep the mix of frame kinds honest: all-text-heavy frames flatter
late interaction by construction. Then strip the _ fields and save as
test/fixtures/imagelane-queries.json.</small></h1>
${rows
  .map(
    (r) => `<div class=card><p class=q>${esc(r.text)}</p>
<p class=meta>evidence: ${esc((r._evidence ?? []).join(" · "))}</p>
<p class=meta>index ${r.index} · ${r.files.length} acceptable frame(s) · session <code>${esc(r.sessionId)}</code> · t_mono ${r._tMono}</p>
<div class=shots>${r.files.map((f) => `<img src="${f}" loading=lazy title="${esc(f)}">`).join("")}</div></div>`,
  )
  .join("\n")}`,
  );
  console.log(`wrote ${rows.length} frames + index.html to ${outDir}`);
  console.log(`scratch: ${dir}`);
}

/**
 * Each candidate owns its own namespace via namespaceFor, so all three index
 * into ONE scratch store without colliding — that is what makes a single run
 * comparable rather than three runs with different scopes.
 *
 * `none` is the honest baseline: what the FREE lanes already return, with no
 * image model at all. It needs no weights, which is also why it is the only arm
 * a default install actually has.
 */
function candidates(models) {
  return [
    { name: "none (lexical + AX FTS only)", kind: "none" },
    {
      name: "nomic-embed-vision-v1.5",
      kind: "single",
      make: async () => {
        const { OnnxImageEmbedding } = await import("../dist/embed/onnx/image.js");
        const dir = join(models, "nomic-embed-vision-v1.5");
        return new OnnxImageEmbedding({
          modelPath: join(dir, "model_int8.onnx"),
          preprocessorPath: join(dir, "preprocessor_config.json"),
        });
      },
    },
    {
      name: "colsmol-256m",
      kind: "multi",
      make: async () => {
        const { ColSmolMultiVector } = await import("../dist/embed/onnx/colsmol.js");
        const dir = join(models, "colSmol-256M-dynamic");
        return new ColSmolMultiVector({
          modelPath: join(dir, "model.onnx"),
          tokenizerPath: join(dir, "tokenizer.json"),
        });
      },
    },
    {
      name: "colmodernvbert-250m",
      kind: "multi",
      make: async () => {
        const { ColModernVBertMultiVector } = await import("../dist/embed/onnx/colmodernvbert.js");
        const dir = join(models, "colmodernvbert-250m");
        return new ColModernVBertMultiVector({
          modelPath: join(dir, "model.onnx"),
          tokenizerPath: join(dir, "tokenizer.json"),
        });
      },
    },
  ];
}

async function indexCandidate(store, blobs, c, sessionIds) {
  if (c.kind === "none") return { embedder: null, frames: 0, vectors: 0, msPerFrame: 0 };
  const embedder = await c.make();
  const { FrameRepresenter } = await import("../dist/represent/frame-representer.js");
  const { FramePatchRepresenter } = await import("../dist/represent/frame-patch-representer.js");

  const t0 = Date.now();
  let frames = 0;
  let vectors = 0;
  for (const id of sessionIds) {
    const r =
      c.kind === "single"
        ? new FrameRepresenter(store, { imageEmbedder: embedder, blobStore: blobs })
        : new FramePatchRepresenter(store, { patchEmbedder: embedder, blobStore: blobs });
    await r.ensureSpace();
    const res = await r.represent(id);
    frames += res.frameCount;
    vectors += res.embeddedCount;
    process.stdout.write(
      `\r  indexed ${vectors}/${frames} frames (${((Date.now() - t0) / 1000).toFixed(0)}s)   `,
    );
  }
  process.stdout.write("\n");
  const ms = Date.now() - t0;
  return { embedder, frames, vectors, msPerFrame: frames ? ms / frames : 0 };
}

/**
 * Rank of the first ACCEPTABLE frame. Ground truth is a set, not a single id —
 * see propose(): consecutive keyframes of one screen are indistinguishable to a
 * person, so demanding a specific one measures noise.
 */
const rankOf = (hits, expected) => {
  const want = new Set(expected);
  const i = hits.findIndex((h) => want.has(h.frameId));
  return i < 0 ? Infinity : i + 1;
};

const summarise = (ranks) => {
  const finite = ranks.filter((r) => Number.isFinite(r));
  const n = ranks.length || 1;
  return {
    n: ranks.length,
    "recall@1": +(ranks.filter((r) => r <= 1).length / n).toFixed(3),
    "recall@5": +(ranks.filter((r) => r <= 5).length / n).toFixed(3),
    "recall@10": +(ranks.filter((r) => r <= 10).length / n).toFixed(3),
    mrr: +(ranks.reduce((a, r) => a + (Number.isFinite(r) ? 1 / r : 0), 0) / n).toFixed(3),
    meanRank: finite.length
      ? +(finite.reduce((a, r) => a + r, 0) / finite.length).toFixed(1)
      : null,
    missed: ranks.length - finite.length,
  };
};

/** The image lane ALONE — no lexical, no segment scope. Isolates the model. */
async function scoreLane(store, c, indexed, queries) {
  if (c.kind === "none") {
    return { supported: false, why: "there is no lane to isolate" };
  }
  if (c.kind === "single") {
    return {
      supported: false,
      why: "text never reaches a nomic frame vector: sharedTextSpace is false and Tier2Retriever requires query.image",
    };
  }
  const { Tier2MultiVectorRetriever } = await import("../dist/retrieve/tier2-mv.js");
  const t2 = new Tier2MultiVectorRetriever(store, indexed.embedder, { topN: 50 });
  const ranks = [];
  let totalMs = 0;
  for (const q of queries) {
    const t0 = Date.now();
    const qv = await t2.embedQuery({ text: q.text });
    const hits = qv ? await t2.retrieveFramesUnscoped(qv) : [];
    totalMs += Date.now() - t0;
    ranks.push(rankOf(hits, q.frameIds));
  }
  return { supported: true, ...summarise(ranks), msPerQuery: Math.round(totalMs / queries.length) };
}

/**
 * The whole system as a user would run it: every free lane, plus this
 * candidate's image lane. This is the number the simplification spec needs —
 * "does adding the lane improve retrieval" is a question about the system, not
 * about the lane in isolation.
 */
async function scoreSystem(store, c, indexed, queries) {
  const { Retriever } = await import("../dist/retrieve/assemble.js");
  const { LexicalSegmentSearcher } = await import("../dist/retrieve/searchers.js");
  const r = new Retriever(
    store,
    {
      searchers: [],
      lexical: new LexicalSegmentSearcher(store),
      ...(c.kind === "single" ? { imageEmbedder: indexed.embedder } : {}),
      ...(c.kind === "multi" ? { patchEmbedder: indexed.embedder } : {}),
    },
    { finalTopN: 50 },
  );
  const ranks = [];
  let totalMs = 0;
  for (const q of queries) {
    const t0 = Date.now();
    const res = await r.retrieve({ text: q.text });
    totalMs += Date.now() - t0;
    ranks.push(rankOf(res.frames, q.frameIds));
  }
  return { supported: true, ...summarise(ranks), msPerQuery: Math.round(totalMs / queries.length) };
}

/** Visual-example arm: a frame as the query, expecting a different frame. */
async function scoreVisual(store, blobs, c, indexed, visualQueries) {
  if (c.kind === "none" || visualQueries.length === 0) {
    return {
      supported: c.kind !== "none",
      n: 0,
      note: c.kind === "none" ? "no image lane" : "no visual pairs in this library",
    };
  }
  const { Tier2Retriever } = await import("../dist/retrieve/tier2.js");
  const { Tier2MultiVectorRetriever } = await import("../dist/retrieve/tier2-mv.js");
  const ranks = [];
  let totalMs = 0;
  for (const q of visualQueries) {
    const frame = store.getFrame(q.queryFrameId);
    const blob = frame?.blobId ? store.getBlob(frame.blobId) : undefined;
    if (!blob) continue;
    const bytes = await blobs.read(blob);
    const t0 = Date.now();
    let hits;
    if (c.kind === "single") {
      const t2 = new Tier2Retriever(store, indexed.embedder, { topN: 50 });
      hits = await t2.retrieveFramesUnscoped({ image: bytes });
    } else {
      const t2 = new Tier2MultiVectorRetriever(store, indexed.embedder, { topN: 50 });
      const qv = await t2.embedQuery({ image: bytes });
      hits = qv ? await t2.retrieveFramesUnscoped(qv) : [];
    }
    totalMs += Date.now() - t0;
    ranks.push(rankOf(hits.filter((h) => h.frameId !== q.queryFrameId), [q.expectFrameId]));
  }
  return {
    supported: true,
    ...summarise(ranks),
    msPerQuery: Math.round(totalMs / Math.max(1, ranks.length)),
  };
}

async function run(models) {
  if (!models) {
    console.error("usage: node scripts/imagelane-probe.mjs --run <modelsDir>");
    process.exit(1);
  }
  const reuse = arg("--scratch", null);
  const dir = reuse ?? openScratchCopy();
  console.log(`scratch: ${dir}`);
  const store = await openStore(dir);
  // The real blobs dir, opened for READING only — it is never copied because a
  // library of JPEGs and MP4s is large, and nothing here writes to it.
  const blobs = new BlobStore(join(DATA_DIR, "blobs"));

  const fixturePath = has("--draft")
    ? "test/fixtures/imagelane-queries.draft.json"
    : "test/fixtures/imagelane-queries.json";
  const fixture = JSON.parse(readFileSync(fixturePath, "utf8"));
  console.log(`queries: ${fixture.queries.length} from ${fixturePath}`);

  const limit = Number(arg("--sessions", "0"));
  const allSessions = store.listSessions().map((s) => s.id);
  // A subset is chosen by QUERY COVERAGE, never by recency: listSessions() is
  // newest-first, and the newest recordings here carry no queries at all, so
  // `--sessions 2` scored zero queries against a fully indexed store — a run
  // that looks like a result and measures nothing.
  const byCoverage = [...allSessions].sort(
    (a, b) =>
      fixture.queries.filter((q) => q.sessionId === b).length -
      fixture.queries.filter((q) => q.sessionId === a).length,
  );
  const sessionIds = limit > 0 ? byCoverage.slice(0, limit) : allSessions;
  // With a session subset, only queries whose answers live in it are meaningful.
  const inScope = new Set(sessionIds);
  const queries = fixture.queries.filter((q) => inScope.has(q.sessionId));
  console.log(
    `sessions: ${sessionIds.length}/${allSessions.length}, queries in scope: ${queries.length}`,
  );
  if (queries.length === 0) {
    console.error("no queries in scope — nothing to measure");
    process.exit(1);
  }

  const only = process.argv.filter((_, i) => process.argv[i - 1] === "--only");
  const results = [];

  for (const c of candidates(models)) {
    if (only.length > 0 && !only.some((o) => c.name.includes(o))) continue;
    console.log(`\n=== ${c.name} ===`);
    const indexed = has("--skip-index")
      ? { embedder: c.kind === "none" ? null : await c.make(), frames: 0, vectors: 0, msPerFrame: 0 }
      : await indexCandidate(store, blobs, c, sessionIds);

    const lane = await scoreLane(store, c, indexed, queries);
    const system = await scoreSystem(store, c, indexed, queries);
    const visual = await scoreVisual(store, blobs, c, indexed, fixture.visualQueries ?? []);
    console.log("  lane  ", JSON.stringify(lane));
    console.log("  system", JSON.stringify(system));
    console.log("  visual", JSON.stringify(visual));
    results.push({
      candidate: c.name,
      indexed: {
        frames: indexed.frames,
        vectors: indexed.vectors,
        msPerFrame: Math.round(indexed.msPerFrame),
      },
      lane,
      system,
      visual,
    });
  }

  const outPath = join(dir, "imagelane-results.json");
  writeFileSync(outPath, JSON.stringify({ queries: queries.length, results }, null, 2));
  console.log(`\nresults: ${outPath}`);
  store.close();
}

if (has("--spaces")) await spaces();
if (has("--propose")) await propose();
const framesAt = process.argv.indexOf("--frames");
if (framesAt >= 0) await extractFrames(process.argv[framesAt + 1] ?? "./imagelane-frames");
if (has("--run")) await run(arg("--run", process.env.DESKRAG_MODELS_DIR));
